services:
  # Наш Go Backend
  - type: web
    name: foodsave-backend
    env: docker
    region: frankfurt
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodsave-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://foodsave-frontend.onrender.com

  # Наш Next.js Frontend
  - type: web
    name: foodsave-frontend
    env: docker
    region: frankfurt
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://foodsave-backend.onrender.com

    # We must pass the NEXT_PUBLIC_API_URL as a buildArg for Next.js to embed it into the frontend bundle
    dockerBuildArgs:
      - NEXT_PUBLIC_API_URL=https://foodsave-backend.onrender.com

databases:
  # База данных PostgreSQL
  - name: foodsave-db
    region: frankfurt
    plan: free
    databaseName: vapor_database
    user: vapor_username
